import './globals.css';
import MainHeader from '@/components/header/main-header';

export const metadata = {
  title: 'Netfliks',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
